### ISSUE TITLE
Dheeraj bhai Kernel restart karke Code rerun kar 

### ISSUE THREAD

**Issue by KJKR73** [Dheeraj-1999/mission-retina#1]
Bro most of your code has undefined or stray output. Please import Libraries from now on.

Thank you, 
Regards

**Comment by Dheeraj-1999** [comment]
bro code is not updated yet! It is old and scrap code. I'll do definitely certain changes in upcoming days!

**Comment by KJKR73** [comment]
Ok no problem 👍
